label: Book_Info_product
path_dirs: ./Log_Metric_DAG/data/0517/common_log_metric_data.pkl
name: Pod_Name
online_start: 1621080836
failure_time: 1621131120
metrics:
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: catalogue-8667bb6cbc-hqzfw

