label: book_info
log_label: ratings.book-info.svc.cluster.local:9080/*
metric_path: ../../data/20231221/
golden_signal_path: ../../data/20231221/pod_level_log_golden_signal.npy
frequency_path: ../../data/20231221/pod_level_log_frequency.npy
kpi_path: ../../data/20231221/kpi.csv
name: Pod_Name
online_start: 1703029951
#80000 1703034951
#75000 1703029951
#70000 1703024951

failure_time: 1703039525
metrics:
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: ratings-aggregated
