label: book_info
path_dirs: ./Log_Metric_DAG/data/1221/common_log_metric_data.pkl
name: Pod_Name
online_start: 1703029951
#80000 1703034951
#75000 1703029951
#70000 1703024951

failure_time: 1703039525
metrics:
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: ratings-aggregated
