label: reviews-v3
path_dirs: ./Log_Metric_DAG/data/0606/common_log_metric_data.pkl
name: Pod_Name
online_start: 1654352266
failure_time: 1654373298
metrics:
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: productpage-v1-5f9dbcd669-z2prs

