label: scenario8_app_request
log_label: ratings.book-info.svc.cluster.local:9080/*
metric_path: ../../data/20240124/
golden_signal_path: ../../data/20240124/pod_level_log_golden_signal.npy
frequency_path: ../../data/20240124/pod_level_log_frequency.npy
kpi_path: ../../data/20240124/kpi.csv
name: Pod_Name
online_start: 1706049401

failure_time: 1706065851

metrics:
  cpu_usage: 1
  disk_used: 1
  diskio_reads: 1
  diskio_writes: 1
  memory_used: 1
  netstat_established: 1
  swap_used: 1
root_cause: i-078923fb30cac1ede

