label: pod usage
log_label: ratings.book-info.svc.cluster.local:9080/*
metric_path: ../../data/20240215/
golden_signal_path: ../../data/20240215/pod_level_log_golden_signal.npy
frequency_path: ../../data/20240215/pod_level_log_frequency.npy
kpi_path: ../../data/20240215/kpi.csv
name: Pod_Name
online_start: 1707862200

failure_time: 1707891089
metrics:
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: details-v1-79548dfc8f-b45tm
