label: Book_Info_product
path_dirs: ./Log_Metric_DAG/data/0524/common_log_metric_data.pkl
name: Pod_Name
online_start: 1621715202
failure_time: 1621736580
metrics: 
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: catalogue-85fd4965b7-q8477

