label: reviews-v3
log_label: ratings.book-info.svc.cluster.local:9080/*
metric_path: ../../data/20220606/
golden_signal_path: ../../data/20220606/pod_level_log_golden_signal.npy
frequency_path: ../../data/20220606/pod_level_log_frequency.npy
kpi_path: ../../data/20220606/kpi.csv
name: Pod_Name
online_start: 1654352266
failure_time: 1654373298
metrics:
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: productpage-v1-5f9dbcd669-z2prs

