label: book_info
path_dirs: ./Log_Metric_DAG/data/1207/common_log_metric_data.pkl
name: Pod_Name
online_start: 1701934867
failure_time: 1701945164

metrics:
  cpu_usage: 1
  memory_usage: 1
  rate_transmitted_packets: 1
  rate_received_packets: 1
  received_bandwidth: 1
  transmit_bandwidth: 1
root_cause: productpage-v1-94d68db49-vc8ct

